### ISSUE TITLE
Can't install and run

### ISSUE THREAD

**Issue by ricardorover** [pinax/pinax-documents#28]
Hi, I followed the installation steps (https://github.com/pinax/pinax-documents#installation) - making the appropriated changes for Django 2.0, but yet when running the project it says:
```
ModuleNotFoundError: No module named 'account'
```

I tried to install https://github.com/pinax/django-user-accounts that appears to be the missing dependency, but I couldn't install and run it on django 2.0 (gave other errors).

Could anyone help on this matter?

**Comment by grahamu** [comment]
@ricardorover thanks for reporting this. I see the problem in [views.py](https://github.com/pinax/pinax-documents/blob/master/pinax/documents/views.py#L20). pinax-documents should not require django-user-accounts.

I'll fix this dependency and publish a new release.

**Comment by ricardorover** [comment]
@grahamu Awesome, thanks! I'll be happy to test it when the release is ready.

**Comment by grahamu** [comment]
@ricardorover we just published pinax-documents v1.0.2 on PyPi. I'd appreciate your testing at your convenience and responding here. pinax-documents no longer requires django-user-accounts, although they still play nicely together. Please close this issue if this fixes your problem, thanks!

**Comment by ricardorover** [comment]
Yes, it resolved the problem. Thanks!

**Comment by grahamu** [comment]
Glad this helped @ricardorover, thanks for your report!
