### ISSUE TITLE
Implement document deletion

### ISSUE THREAD

**Issue by jacobwegner** [pinax/pinax-documents#3]
The [`document_delete`](https://github.com/pinax/pinax-documents/blob/9b94e6b9d084c0ba17b6e22f466bade281583364/pinax/documents/views.py#L184) view doesn't actually delete the `Document` model.

In addition, I think it is reasonable to remove the `file` from disk/project's storage backend, probably implemented with a `pre_delete` signal.

**Comment by ethankent** [comment]
Hi,

I have a pull request out for this: https://github.com/pinax/pinax-documents/pull/17, but it's failing because it requires another pull request: https://github.com/pinax/pinax-theme-bootstrap/pull/115

**Comment by ethankent** [comment]
Looks like everything is up-to-date now. Thanks for your help. I think we could probably even close off this issue and check it off the Milestone List: https://github.com/pinax/pinax-starter-projects/wiki/Groupware-Starter-Project

**Comment by paltman** [comment]
@ethankent Awesome!  Just one more left for `pinax-documents`.  Nice work!
