### ISSUE TITLE
Rewrite views as class based views

### ISSUE THREAD

**Issue by paltman** [pinax/pinax-documents#5]
Currently there is a mix of function and class-based views.  We should ship with CBVs to allow for greater extensibility.
- `folder_create` => `FolderCreateView(LoginRequiredMixin, CreateView)`
- `folder_detail` => `FolderDetailView(LoginRequiredMixin, DetailView)`
- `document_create` => `DocumentCreateView(LoginRequiredMixin, CreateView)`
- `document_detail` => `DocumentDetailView(LoginRequiredMixin, DetailView)`
- `document_download` => `DocumentDownloadView(LoginRequiredMixin, View)` (but maybe a `DetailView`)
- `folder_share` => `FolderShareView(LoginRequiredMixin, View)` (but maybe a `DetailView`)
- `document_delete` => `DocumentDeleteView(LoginRequiredMixin, DeleteView)`

**Comment by grahamu** [comment]
@paltman Is this issue now resolved?
