### ISSUE TITLE
Move post_save receiver to receivers.py

### ISSUE THREAD

**Issue by paltman** [pinax/pinax-documents#8]
Will also mean you need to setup an apps.py and import the receivers.py module during the `ready` method.

Example: https://github.com/pinax/pinax-stripe/blob/master/pinax/stripe/apps.py#L14 and https://github.com/pinax/pinax-stripe/blob/master/pinax/stripe/__init__.py#L4

**Comment by grahamu** [comment]
@paltman Where are we moving the post_save receiver from? I don't find any post_save handler in the existing pinax-documents project.

**Comment by paltman** [comment]
@grahamu https://github.com/pinax/pinax-documents/blob/master/pinax/documents/models.py#L319

**Comment by grahamu** [comment]
Thanks! No idea why my IDE search didn't find that, but now it does. Hmmm.
